# Regression -Airfoil dataset


In [3]:
import pandas as pd
import numpy as np


In [14]:
names = ['Frequency','Angle','Chord length','velocity','thickness','Sound pressure']

In [18]:
dataset = pd.read_csv('D:\\priyam\\datasetss\\airfoil_self_noise.dat',sep = '\t', header = None,names = names)

In [22]:
dataset

Frequency  Angle  Chord length  velocity  thickness  Sound pressure
0           800    0.0        0.3048      71.3   0.002663         126.201
1          1000    0.0        0.3048      71.3   0.002663         125.201
2          1250    0.0        0.3048      71.3   0.002663         125.951
3          1600    0.0        0.3048      71.3   0.002663         127.591
4          2000    0.0        0.3048      71.3   0.002663         127.461
...         ...    ...           ...       ...        ...             ...
1498       2500   15.6        0.1016      39.6   0.052849         110.264
1499       3150   15.6        0.1016      39.6   0.052849         109.254
1500       4000   15.6        0.1016      39.6   0.052849         106.604
1501       5000   15.6        0.1016      39.6   0.052849         106.224
1502       6300   15.6        0.1016      39.6   0.052849         104.204

[1503 rows x 6 columns]

In [30]:
X = dataset.iloc[:,0:5].values
y = dataset.iloc[:,5].values

In [33]:
y

array([126.201, 125.201, 125.951, ..., 106.604, 106.224, 104.204])

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.25, random_state = 123)

In [36]:
from sklearn.linear_model import LinearRegression

In [37]:
lr = LinearRegression()

In [38]:
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [39]:
lr.coef_

array([-1.26427170e-03, -4.22774919e-01, -3.61455630e+01,  9.78783454e-02,
       -1.50416433e+02])

In [40]:
y_pred = lr.predict(X_test)

In [42]:
y_pred[:20]

array([119.49559841, 125.2046991 , 129.61096798, 127.13349528,
       136.98512179, 127.81452989, 132.7903293 , 128.9975142 ,
       120.28074788, 126.49075593, 125.95181607, 111.15127173,
       116.71409442, 117.18917625, 121.24465439, 126.61683272,
       125.18023698, 128.02112611, 128.12470071, 129.76656649])

In [45]:
y_test[:20]

array([118.145, 132.184, 131.362, 122.612, 130.96 , 127.637, 125.054,
       135.484, 115.996, 128.412, 127.71 , 111.076, 115.91 , 125.683,
       118.024, 129.395, 124.514, 126.842, 129.395, 128.334])

# Logistic regression

logistic regression is used for classification problem even though it predicts continous values

logistic regression = logistic function + multiple linear regression

In [1]:
import pandas as pd
import numpy as np

In [10]:
# area A,
# perimeter P,
# compactness C = 4*pi*A/P^2,
# length of kernel,
# width of kernel,
# asymmetry coefficient
# length of kernel groove

In [16]:
seeds_dataset = pd.read_csv('D:/priyam/datasetss/seeds_dataset.txt',sep = '\t', header = None, names = ['Area','Perimeter', 'compact', 'length', 'width', 'coeff', 'lenght groove', 'class'])

In [24]:
seeds_dataset = seeds_dataset.dropna(how = 'any')

In [25]:
X = seeds_dataset.iloc[:,:-1].values
y = seeds_dataset.iloc[:,-1].values

In [31]:
# seeds_dataset.head(50)

In [30]:
seeds_dataset.shape

(199, 8)

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.30, random_state=123)

In [34]:
X_train.shape

(139, 7)

In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
lr = LogisticRegression()

In [39]:
lr.fit(X_train,y_train) # training

D:\anaconda\envs\tensorflow_env\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [40]:
y_pred = lr.predict(X_test)

In [41]:
y_pred

array([3., 1., 2., 1., 1., 1., 3., 2., 1., 3., 2., 3., 2., 2., 3., 3., 1.,
       3., 2., 1., 3., 3., 3., 3., 2., 3., 3., 2., 3., 3., 3., 2., 3., 1.,
       3., 3., 2., 1., 1., 2., 3., 1., 1., 3., 2., 3., 2., 1., 2., 2., 1.,
       2., 1., 2., 1., 1., 2., 2., 2., 3.])

In [42]:
y_test

array([3., 1., 2., 1., 1., 1., 3., 2., 1., 3., 2., 3., 2., 2., 3., 3., 1.,
       3., 2., 3., 3., 3., 3., 3., 2., 3., 3., 2., 1., 3., 3., 2., 3., 2.,
       3., 3., 2., 1., 1., 2., 3., 1., 1., 3., 1., 3., 2., 1., 2., 2., 1.,
       2., 1., 2., 1., 3., 2., 2., 2., 3.])

In [45]:
from sklearn.metrics import confusion_matrix

In [46]:
confusion_matrix(y_test,y_pred)

array([[14,  1,  1],
       [ 1, 19,  0],
       [ 2,  0, 22]], dtype=int64)