In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset_load = pd.read_csv('genderclassification.csv')

In [3]:
dataset_load.head(5)

Favorite Color Favorite Music Genre Favorite Beverage Favorite Soft Drink  \
0           Cool                 Rock             Vodka          7UP/Sprite   
1        Neutral              Hip hop             Vodka     Coca Cola/Pepsi   
2           Warm                 Rock              Wine     Coca Cola/Pepsi   
3           Warm     Folk/Traditional           Whiskey               Fanta   
4           Cool                 Rock             Vodka     Coca Cola/Pepsi   

  Gender  
0      F  
1      F  
2      F  
3      F  
4      F

In [4]:
dataset_load.columns

Index(['Favorite Color', 'Favorite Music Genre', 'Favorite Beverage',
       'Favorite Soft Drink', 'Gender'],
      dtype='object')

In [5]:
dataset_load.shape

(66, 5)

In [6]:
dataset_load.isnull().sum()

Favorite Color          0
Favorite Music Genre    0
Favorite Beverage       0
Favorite Soft Drink     0
Gender                  0
dtype: int64

In [7]:
dataset_load['Favorite Color'].value_counts()

Cool       37
Warm       22
Neutral     7
Name: Favorite Color, dtype: int64

In [8]:
dataset_load['Favorite Music Genre'].value_counts()

Rock                19
Pop                 17
Electronic           8
Hip hop              8
R&B and soul         6
Folk/Traditional     4
Jazz/Blues           4
Name: Favorite Music Genre, dtype: int64

In [9]:
dataset_load['Favorite Beverage'].value_counts()

Doesn't drink    14
Beer             13
Other            11
Wine             10
Whiskey           9
Vodka             9
Name: Favorite Beverage, dtype: int64

In [10]:
dataset_load['Favorite Soft Drink'].value_counts()

Coca Cola/Pepsi    32
Fanta              14
7UP/Sprite         13
Other               7
Name: Favorite Soft Drink, dtype: int64

In [11]:
dataset_load['Gender'].value_counts()

M    33
F    33
Name: Gender, dtype: int64

In [12]:
dataset_load['Gender'] = dataset_load.Gender.replace(to_replace=['M','F'], value=[1,0])

In [13]:
dataset_load

Favorite Color Favorite Music Genre Favorite Beverage Favorite Soft Drink  \
0            Cool                 Rock             Vodka          7UP/Sprite   
1         Neutral              Hip hop             Vodka     Coca Cola/Pepsi   
2            Warm                 Rock              Wine     Coca Cola/Pepsi   
3            Warm     Folk/Traditional           Whiskey               Fanta   
4            Cool                 Rock             Vodka     Coca Cola/Pepsi   
..            ...                  ...               ...                 ...   
61           Cool                 Rock             Vodka     Coca Cola/Pepsi   
62           Cool              Hip hop              Beer     Coca Cola/Pepsi   
63        Neutral              Hip hop     Doesn't drink               Fanta   
64           Cool                 Rock              Wine     Coca Cola/Pepsi   
65           Cool           Electronic              Beer     Coca Cola/Pepsi   

    Gender  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
61       1  
62       1  
63       1  
64       1  
65       1  

[66 rows x 5 columns]

In [14]:
# creating dummines 
dummy_columns = ['Favorite Color', 'Favorite Music Genre', 'Favorite Beverage',
                'Favorite Soft Drink']

In [15]:
dataset_load = pd.get_dummies(data=dataset_load, columns= dummy_columns)

In [16]:
X = dataset_load.drop('Gender',axis=1).values

In [17]:
y = dataset_load['Gender'].values

In [18]:
X.shape

(66, 20)

In [19]:
y.shape

(66,)

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20,random_state=5)

In [22]:
from sklearn import svm

In [26]:
from sklearn import metrics

In [30]:
from sklearn import linear_model
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

classifiers = [
    svm.SVC(),
    linear_model.LogisticRegression(),
    GaussianNB(),
    linear_model.SGDClassifier(),
    KNeighborsClassifier(n_neighbors=8)]
    
for item in classifiers:
    print(item)
    clf = item
    clf.fit(X_train, y_train)
    print(clf.predict(X_test),'\n')
    print(clf.score(X_test,y_test))

SVC()
[1 0 0 0 0 0 1 1 0 0 1 1 0 1] 

0.5714285714285714
LogisticRegression()
[1 0 0 1 0 0 1 1 1 0 0 1 0 1] 

0.5
GaussianNB()
[0 0 0 0 0 0 1 0 0 0 0 1 0 0] 

0.2857142857142857
SGDClassifier()
[1 0 1 1 0 0 1 1 0 0 0 1 0 0] 

0.42857142857142855
KNeighborsClassifier(n_neighbors=8)
[0 0 0 0 0 0 1 0 0 0 0 0 0 0] 

0.35714285714285715


In [31]:
clf = svm.SVC()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [32]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.5714285714285714


In [33]:
prediction = {"Actual_values" :y_test,
             "Predicted_values": y_pred}

In [36]:
predictions = pd.DataFrame(prediction)

In [37]:
predictions

Actual_values  Predicted_values
0               1                 1
1               0                 0
2               1                 0
3               0                 0
4               0                 0
5               0                 0
6               0                 1
7               1                 1
8               1                 0
9               1                 0
10              1                 1
11              0                 1
12              1                 0
13              1                 1

In [38]:
y_test

array([1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [39]:
y_pred

array([1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1], dtype=int64)

In [47]:
import pickle

In [48]:
filename = 'finalized_model.pkl'
pickle.dump(clf, open(filename, 'wb'))

In [49]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, y_test)
print(result)

0.5714285714285714
